const { Resend } = require("resend");

let resendClient = null;

const getResend = () => {
  if (!process.env.RESEND_API_KEY) {
    const error = new Error("RESEND_API_KEY is not configured on the server.");
    error.statusCode = 500;
    throw error;
  }

  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }

  return resendClient;
};

const escapeHtml = (value) =>
  String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");

const buildDepartmentTimetableEmail = ({
  departmentName,
  roomName,
  slotRows,
  generatedBy,
}) => {
  const rowsHtml = slotRows
    .map(
      (slot) => `
      <tr>
        <td style="padding:10px;border-bottom:1px solid #eef2f7;font-size:13px;color:#1f2937;">${escapeHtml(
          slot.day
        )}</td>
        <td style="padding:10px;border-bottom:1px solid #eef2f7;font-size:13px;color:#1f2937;">P${escapeHtml(
          slot.periodNumber
        )} (${escapeHtml(slot.startTime)} - ${escapeHtml(slot.endTime)})</td>
        <td style="padding:10px;border-bottom:1px solid #eef2f7;font-size:13px;color:#1f2937;">${escapeHtml(
          slot.subject || "-"
        )}</td>
        <td style="padding:10px;border-bottom:1px solid #eef2f7;font-size:13px;color:#1f2937;">${escapeHtml(
          slot.teacher || "-"
        )}</td>
      </tr>
    `
    )
    .join("");

  return `
  <body style="margin:0;padding:0;background:#f4f4f7;font-family:'Segoe UI',Arial,sans-serif;">
    <table width="100%" cellpadding="0" cellspacing="0" style="padding:36px 0;">
      <tr><td align="center">
        <table width="640" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">
          <tr><td style="background:#4F46E5;padding:18px 24px;">
            <span style="font-size:20px;font-weight:700;color:#fff;">GeoFence</span>
          </td></tr>
          <tr><td style="padding:24px;">
            <p style="margin:0 0 8px;font-size:18px;font-weight:700;color:#111827;">Timetable Assignment Notification</p>
            <p style="margin:0 0 6px;font-size:14px;color:#4b5563;">Department: <strong>${escapeHtml(
              departmentName
            )}</strong></p>
            <p style="margin:0 0 6px;font-size:14px;color:#4b5563;">Room: <strong>${escapeHtml(
              roomName
            )}</strong></p>
            <p style="margin:0 0 18px;font-size:13px;color:#6b7280;">Generated by: ${escapeHtml(
              generatedBy
            )}</p>

            <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #eef2f7;border-radius:8px;overflow:hidden;">
              <thead>
                <tr style="background:#f8fafc;">
                  <th align="left" style="padding:10px;font-size:12px;color:#334155;border-bottom:1px solid #eef2f7;">Day</th>
                  <th align="left" style="padding:10px;font-size:12px;color:#334155;border-bottom:1px solid #eef2f7;">Period</th>
                  <th align="left" style="padding:10px;font-size:12px;color:#334155;border-bottom:1px solid #eef2f7;">Subject</th>
                  <th align="left" style="padding:10px;font-size:12px;color:#334155;border-bottom:1px solid #eef2f7;">Teacher</th>
                </tr>
              </thead>
              <tbody>
                ${rowsHtml}
              </tbody>
            </table>

            <p style="margin:18px 0 0;font-size:12px;color:#9ca3af;">This is an automated message from the timetable system.</p>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
  `;
};

const sendDepartmentTimetableEmail = async ({
  to,
  departmentName,
  roomName,
  slotRows,
  generatedBy,
}) => {
  const from = process.env.RESEND_FROM || "GeoFence <noreply@geoforms.in>";
  const subject = `Timetable Slots Assigned - ${departmentName}`;

  const { data, error } = await getResend().emails.send({
    from,
    to,
    subject,
    html: buildDepartmentTimetableEmail({
      departmentName,
      roomName,
      slotRows,
      generatedBy,
    }),
  });

  if (error) {
    const err = new Error(`Failed to send timetable email to ${to}: ${error.message}`);
    err.statusCode = 502;
    throw err;
  }

  return data;
};

module.exports = {
  sendDepartmentTimetableEmail,
};
